name: 🚀 React - Gatsby - Web Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Gatsby build
      run: |
        npm ci
        npm run build
        # npm test
        
    # - name: 📂 Sync files with FTP
    #   if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.2
    #   with:
    #     server: ${{ secrets.FTP_HOST }}
    #     username: ${{ secrets.FTP_USER }}
    #     password: ${{ secrets.FTP_PASSSWORD }}
    #     local-dir: ./public/
    #     server-dir: public_html/
